export default {
  entrada1: { valor: 'entrada1' },
  entrada2: { valor: 'entrada2' },
  r: { valor: 'r' },
  entrada3: { valor: 'entrada3' },
  j: { valor: 'j' },
  f: { valor: 'f' },
  c: { valor: 'c' },
  b: { valor: 'b' },
  a: { valor: 'a' },
  g: { valor: 'g' },
  h: { valor: 'h' },
  e: { valor: 'e' },
  d: { valor: 'd' },
  i: { valor: 'i' },
  k: { valor: 'k' },
  l: { valor: 'l' },
  o: { valor: 'o' },
  p: { valor: 'p' },
}